stages:
  - build

services:
  - docker:dind
before_script:
  - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY

build:
  stage: build
  tags:
    - docker
    - dind
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull -t registry.nocsi.org/trufflehog:latest -t "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME"
    - docker push registry.nocsi.org/trufflehog:latest
  only:
    - master
